apiVersion: v1
kind: Service
metadata:
  name: '{{.Values.microservices.mysvc.serviceName}}'
spec:
  selector:
    app: '{{.Values.microservices.mysvc.serviceName}}'
  ports:
  - name: http
    port: 80
    targetPort: '{{.Values.microservices.mysvc.containerPort}}'
  type: ClusterIP
